import { Artikel, Liga, LIGEN } from "./types";

// Unsplash Fußball-Bilder
const IMAGES = {
  stadion: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800",
  action: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800",
  fans: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800",
  rasen: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800",
  tor: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800",
  ball: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800",
  flutlicht: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800",
};

export const artikel: Artikel[] = [
  // === BUNDESLIGA (5 Artikel) ===
  {
    id: "1",
    titel: "Stürmer-Spektakel aus dem Lehrbuch",
    slug: "stuermer-spektakel-union-frankfurt",
    teaser: "Der Sieg des 1. FC Union in Frankfurt entspringt einer taktischen Meisterleistung. Ein Triumph in ungeahnter Dimension.",
    bild: { url: IMAGES.action, alt: "Union Berlin Spielszene", credit: "Foto: Koch" },
    datum: "2025-02-03T10:00:00Z",
    kategorie: "spielbericht",
    ligaId: "bundesliga-1",
    autor: { name: "Robert Klein" },
    lesedauer: 6,
    featured: true,
    tags: ["1. FC Union Berlin", "Eintracht Frankfurt", "Bundesliga"],
  },
  {
    id: "2",
    titel: "Aufstiegskampf spitzt sich zu",
    slug: "aufstiegskampf-bundesliga",
    teaser: "Drei Punkte trennen die Top 5 der Tabelle. Der Saisonendspurt verspricht Spannung pur.",
    bild: { url: IMAGES.flutlicht, alt: "Bundesliga Flutlicht", credit: "Foto: Meyer" },
    datum: "2025-02-02T14:00:00Z",
    kategorie: "analyse",
    ligaId: "bundesliga-1",
    autor: { name: "Lisa Schmidt" },
    lesedauer: 4,
    tags: ["Bundesliga", "Tabelle", "Aufstiegskampf"],
  },
  {
    id: "3",
    titel: "Trainer nach Niederlage unter Druck",
    slug: "trainer-unter-druck-bundesliga",
    teaser: "Nach der dritten Pleite in Folge wackelt der Stuhl des Übungsleiters.",
    bild: { url: IMAGES.rasen, alt: "Spielfeld", credit: "Foto: Weber" },
    datum: "2025-02-01T18:00:00Z",
    kategorie: "news",
    ligaId: "bundesliga-1",
    autor: { name: "Thomas Müller" },
    lesedauer: 3,
    tags: ["Bundesliga", "Trainer"],
  },
  {
    id: "4",
    titel: "Neuzugang überzeugt beim Debüt",
    slug: "neuzugang-debuet-bundesliga",
    teaser: "Der Winter-Transfer zeigt sofort, warum der Verein tief in die Tasche gegriffen hat.",
    bild: { url: IMAGES.ball, alt: "Fußball", credit: "Foto: Schulz" },
    datum: "2025-01-31T12:00:00Z",
    kategorie: "spielbericht",
    ligaId: "bundesliga-1",
    autor: { name: "Anna Becker" },
    lesedauer: 5,
    tags: ["Bundesliga", "Transfer", "Neuzugang"],
  },
  {
    id: "5",
    titel: "Rekordtransfer vor dem Absprung",
    slug: "rekordtransfer-bundesliga",
    teaser: "Gerüchte um einen Wechsel nach England verdichten sich. Ablöse könnte 50 Millionen übersteigen.",
    bild: { url: IMAGES.stadion, alt: "Stadion", credit: "Foto: Richter" },
    datum: "2025-01-30T09:00:00Z",
    kategorie: "transfer",
    ligaId: "bundesliga-1",
    autor: { name: "Max Hoffmann" },
    lesedauer: 4,
    tags: ["Bundesliga", "Transfer", "Premier League"],
  },

  // === 2. BUNDESLIGA (5 Artikel) ===
  {
    id: "6",
    titel: "Der Abstiegszone gefährlich nah",
    slug: "hertha-abstiegszone-heimschwaeche",
    teaser: "Ohne Überwindung der Heimschwäche wird Hertha BSC nicht oben mitspielen können.",
    bild: { url: IMAGES.stadion, alt: "Olympiastadion Berlin", credit: "Foto: Winter" },
    datum: "2025-02-02T14:00:00Z",
    kategorie: "analyse",
    ligaId: "bundesliga-2",
    autor: { name: "Karsten Doneck" },
    lesedauer: 5,
    tags: ["Hertha BSC", "2. Bundesliga", "Berlin", "Olympiastadion"],
  },
  {
    id: "7",
    titel: "Derbysieg befeuert Aufstiegshoffnung",
    slug: "derbysieg-zweite-liga",
    teaser: "Mit dem prestigeträchtigen Erfolg klettert das Team auf Platz drei der Tabelle.",
    bild: { url: IMAGES.fans, alt: "Derbysieg Jubel", credit: "Foto: Koch" },
    datum: "2025-02-01T20:00:00Z",
    kategorie: "spielbericht",
    ligaId: "bundesliga-2",
    autor: { name: "Michael Braun" },
    lesedauer: 4,
    tags: ["2. Bundesliga", "Derby", "Aufstieg"],
  },
  {
    id: "8",
    titel: "Kapitän verlängert bis 2028",
    slug: "kapitaen-verlaengert-zweite-liga",
    teaser: "Der Führungsspieler bekennt sich zum Verein und unterschreibt einen neuen Dreijahresvertrag.",
    bild: { url: IMAGES.action, alt: "Spielszene", credit: "Foto: Richter" },
    datum: "2025-01-30T10:00:00Z",
    kategorie: "transfer",
    ligaId: "bundesliga-2",
    autor: { name: "Sandra Klein" },
    lesedauer: 3,
    tags: ["2. Bundesliga", "Vertrag", "Kapitän"],
  },
  {
    id: "9",
    titel: "Torjäger meldet sich fit zurück",
    slug: "torjaeger-fit-zweite-liga",
    teaser: "Nach wochenlanger Verletzungspause steht der Goalgetter vor dem Comeback.",
    bild: { url: IMAGES.tor, alt: "Tornetz", credit: "Foto: Berger" },
    datum: "2025-01-29T16:00:00Z",
    kategorie: "news",
    ligaId: "bundesliga-2",
    autor: { name: "Peter Hoffmann" },
    lesedauer: 2,
    tags: ["2. Bundesliga", "Comeback", "Verletzung"],
  },
  {
    id: "10",
    titel: "Stadion-Neubau endlich genehmigt",
    slug: "stadion-neubau-zweite-liga",
    teaser: "Nach jahrelangem Ringen gibt die Stadt grünes Licht für die neue Arena.",
    bild: { url: IMAGES.flutlicht, alt: "Flutlicht", credit: "Foto: Lang" },
    datum: "2025-01-28T11:00:00Z",
    kategorie: "news",
    ligaId: "bundesliga-2",
    autor: { name: "Claudia Weber" },
    lesedauer: 4,
    tags: ["2. Bundesliga", "Stadion", "Neubau"],
  },

  // === 3. LIGA (5 Artikel) ===
  {
    id: "11",
    titel: "Tabellenführer patzt überraschend",
    slug: "tabellenfuehrer-patzt-dritte-liga",
    teaser: "Der Spitzenreiter verliert erstmals seit zehn Spielen und die Verfolger wittern ihre Chance.",
    bild: { url: IMAGES.action, alt: "3. Liga Action", credit: "Foto: Schmidt" },
    datum: "2025-02-03T15:00:00Z",
    kategorie: "spielbericht",
    ligaId: "liga-3",
    autor: { name: "Frank Weber" },
    lesedauer: 4,
    tags: ["3. Liga", "Tabellenführer", "Überraschung"],
  },
  {
    id: "12",
    titel: "Aufsteiger überrascht die Liga",
    slug: "aufsteiger-ueberrascht-dritte-liga",
    teaser: "Der Neuling mischt die Konkurrenz auf und steht sensationell auf einem Aufstiegsplatz.",
    bild: { url: IMAGES.fans, alt: "Aufsteiger Fans", credit: "Foto: Lange" },
    datum: "2025-02-02T12:00:00Z",
    kategorie: "analyse",
    ligaId: "liga-3",
    autor: { name: "Julia Hartmann" },
    lesedauer: 5,
    tags: ["3. Liga", "Aufsteiger", "Aufstieg"],
  },
  {
    id: "13",
    titel: "Nachwuchstalent feiert Profidebüt",
    slug: "nachwuchstalent-dritte-liga",
    teaser: "Mit 17 Jahren steht der Youngster erstmals in der Startelf und liefert sofort ab.",
    bild: { url: IMAGES.ball, alt: "Fußball Close-up", credit: "Foto: Krause" },
    datum: "2025-02-01T14:00:00Z",
    kategorie: "news",
    ligaId: "liga-3",
    autor: { name: "Markus Fischer" },
    lesedauer: 3,
    tags: ["3. Liga", "Nachwuchs", "Debüt"],
  },
  {
    id: "14",
    titel: "Stadionausbau wird konkreter",
    slug: "stadionausbau-dritte-liga",
    teaser: "Die Pläne für die Erweiterung der Arena nehmen Form an. Baubeginn soll 2026 sein.",
    bild: { url: IMAGES.stadion, alt: "Stadion", credit: "Foto: Wolf" },
    datum: "2025-01-31T09:00:00Z",
    kategorie: "news",
    ligaId: "liga-3",
    autor: { name: "Claudia Neumann" },
    lesedauer: 4,
    tags: ["3. Liga", "Stadion", "Ausbau"],
  },
  {
    id: "15",
    titel: "Elfmeterkiller hält Sieg fest",
    slug: "elfmeterkiller-dritte-liga",
    teaser: "Der Keeper pariert zwei Strafstöße und sichert seinem Team drei wichtige Punkte.",
    bild: { url: IMAGES.tor, alt: "Torwart", credit: "Foto: Engel" },
    datum: "2025-01-30T18:00:00Z",
    kategorie: "spielbericht",
    ligaId: "liga-3",
    autor: { name: "Stefan Roth" },
    lesedauer: 3,
    tags: ["3. Liga", "Torwart", "Elfmeter"],
  },

  // === REGIONALLIGA NORDOST (5 Artikel) ===
  {
    id: "16",
    titel: "Altglienicke schiebt sich immer weiter vor",
    slug: "altglienicke-tabellenspitze-regionalliga",
    teaser: "Heimlich, still und gar nicht leise pirscht sich die VSG an die Ligaspitze heran.",
    bild: { url: IMAGES.rasen, alt: "VSG Altglienicke", credit: "Foto: Kellner" },
    datum: "2025-02-01T16:00:00Z",
    kategorie: "analyse",
    ligaId: "regionalliga-nordost",
    autor: { name: "Harri Ramin" },
    lesedauer: 4,
    tags: ["VSG Altglienicke", "Regionalliga", "Berlin"],
  },
  {
    id: "17",
    titel: "BFC Preussen sorgt für Furore",
    slug: "bfc-preussen-regionalliga",
    teaser: "Der Aufsteiger gewinnt das dritte Spiel in Folge und etabliert sich im oberen Tabellendrittel.",
    bild: { url: IMAGES.fans, alt: "BFC Preussen Fans", credit: "Foto: Schulze" },
    datum: "2025-01-31T18:00:00Z",
    kategorie: "spielbericht",
    ligaId: "regionalliga-nordost",
    autor: { name: "Dirk Baumann" },
    lesedauer: 3,
    tags: ["BFC Preussen", "Regionalliga", "Berlin"],
  },
  {
    id: "18",
    titel: "Lok Leipzig verteidigt Tabellenführung",
    slug: "lok-leipzig-regionalliga",
    teaser: "Der Titelverteidiger lässt nichts anbrennen und baut den Vorsprung aus.",
    bild: { url: IMAGES.action, alt: "Lok Leipzig", credit: "Foto: Friedrich" },
    datum: "2025-01-30T20:00:00Z",
    kategorie: "spielbericht",
    ligaId: "regionalliga-nordost",
    autor: { name: "Steffen Krug" },
    lesedauer: 4,
    tags: ["1. FC Lok Leipzig", "Regionalliga", "Tabellenführer"],
  },
  {
    id: "19",
    titel: "Transfercoup für Berliner Verein",
    slug: "transfercoup-regionalliga",
    teaser: "Ein ehemaliger Zweitligaspieler wechselt in die Regionalliga und sorgt für Aufsehen.",
    bild: { url: IMAGES.flutlicht, alt: "Flutlicht Abend", credit: "Foto: Engel" },
    datum: "2025-01-29T11:00:00Z",
    kategorie: "transfer",
    ligaId: "regionalliga-nordost",
    autor: { name: "Nina Vogel" },
    lesedauer: 3,
    tags: ["Regionalliga", "Transfer", "Berlin"],
  },
  {
    id: "20",
    titel: "Hallescher FC in der Krise",
    slug: "halle-krise-regionalliga",
    teaser: "Nach drei Niederlagen in Serie gerät der Favorit ins Straucheln. Trainer zählt das Team an.",
    bild: { url: IMAGES.stadion, alt: "Halle Stadion", credit: "Foto: Meier" },
    datum: "2025-01-28T14:00:00Z",
    kategorie: "analyse",
    ligaId: "regionalliga-nordost",
    autor: { name: "Jens Lehmann" },
    lesedauer: 5,
    tags: ["Hallescher FC", "Regionalliga", "Krise"],
  },

  // === OBERLIGA NOFV NORD (5 Artikel) ===
  {
    id: "21",
    titel: "Die Sache mit dem glücklichen Händchen",
    slug: "hertha-03-zwickau-oberliga",
    teaser: "Der zur Pause eingewechselte von Baer benötigt nur vier Minuten für den Siegtreffer.",
    bild: { url: IMAGES.tor, alt: "Oberliga Spiel", credit: "Foto: Koch" },
    datum: "2025-01-31T18:00:00Z",
    kategorie: "spielbericht",
    ligaId: "oberliga-nofv-nord",
    autor: { name: "Matthias Schütt" },
    lesedauer: 3,
    tags: ["Hertha 03 Zehlendorf", "Oberliga", "Berlin"],
  },
  {
    id: "22",
    titel: "Abstiegskampf wird zur Nervenschlacht",
    slug: "abstiegskampf-oberliga",
    teaser: "Im Tabellenkeller trennen nur vier Punkte sechs Mannschaften. Jedes Spiel zählt.",
    bild: { url: IMAGES.fans, alt: "Oberliga Fans", credit: "Foto: Hartwig" },
    datum: "2025-01-30T14:00:00Z",
    kategorie: "analyse",
    ligaId: "oberliga-nofv-nord",
    autor: { name: "Oliver Thiel" },
    lesedauer: 5,
    tags: ["Oberliga", "Abstiegskampf"],
  },
  {
    id: "23",
    titel: "Spielertrainer übernimmt Verantwortung",
    slug: "spielertrainer-oberliga",
    teaser: "Nach der Trennung vom Coach springt ein Routinier als Interimslösung ein.",
    bild: { url: IMAGES.ball, alt: "Fußball", credit: "Foto: Berger" },
    datum: "2025-01-29T10:00:00Z",
    kategorie: "news",
    ligaId: "oberliga-nofv-nord",
    autor: { name: "Carsten Wolff" },
    lesedauer: 3,
    tags: ["Oberliga", "Trainer", "Spielertrainer"],
  },
  {
    id: "24",
    titel: "Pokalüberraschung bahnt sich an",
    slug: "pokalueberraschung-oberliga",
    teaser: "Der Underdog steht überraschend im Halbfinale des Landespokals.",
    bild: { url: IMAGES.action, alt: "Pokaljubel", credit: "Foto: Seidel" },
    datum: "2025-01-28T17:00:00Z",
    kategorie: "spielbericht",
    ligaId: "oberliga-nofv-nord",
    autor: { name: "Ralf Köhler" },
    lesedauer: 4,
    tags: ["Oberliga", "Landespokal", "Pokal"],
  },
  {
    id: "25",
    titel: "Traditionsverein kämpft ums Überleben",
    slug: "traditionsverein-oberliga",
    teaser: "Finanzielle Probleme zwingen den Klub zu drastischen Maßnahmen. Fans starten Spendenaktion.",
    bild: { url: IMAGES.flutlicht, alt: "Flutlicht Stadion", credit: "Foto: Lange" },
    datum: "2025-01-27T12:00:00Z",
    kategorie: "news",
    ligaId: "oberliga-nofv-nord",
    autor: { name: "Bernd Schneider" },
    lesedauer: 6,
    tags: ["Oberliga", "Finanzen", "Fans"],
  },

  // === BERLIN-LIGA (5 Artikel) ===
  {
    id: "26",
    titel: "Stabile Defensive und ein Doppel-Härtel",
    slug: "makkabi-neustrelitz-berlin-liga",
    teaser: "Neustrelitz bringt Makkabi eine Heimniederlage bei – eine Lehrstunde für den Gastgeber.",
    bild: { url: IMAGES.rasen, alt: "Berlin-Liga Spielfeld", credit: "Foto: dedepress" },
    datum: "2025-01-30T15:00:00Z",
    kategorie: "spielbericht",
    ligaId: "berlin-liga",
    autor: { name: "Matthias Schütt" },
    lesedauer: 3,
    tags: ["TuS Makkabi Berlin", "TSV 1860 Neustrelitz", "Berlin-Liga"],
  },
  {
    id: "27",
    titel: "Türkiyemspor zurück auf Kurs",
    slug: "tuerkiyemspor-berlin-liga",
    teaser: "Nach schwachem Saisonstart findet der Traditionsverein zurück in die Spur.",
    bild: { url: IMAGES.action, alt: "Türkiyemspor", credit: "Foto: Yilmaz" },
    datum: "2025-01-29T19:00:00Z",
    kategorie: "analyse",
    ligaId: "berlin-liga",
    autor: { name: "Deniz Özkan" },
    lesedauer: 4,
    tags: ["Türkiyemspor Berlin", "Berlin-Liga", "Kreuzberg"],
  },
  {
    id: "28",
    titel: "Lokalrivalen liefern packendes Derby",
    slug: "derby-berlin-liga",
    teaser: "Vor ausverkauftem Haus trennen sich die Nachbarn nach einem Spektakel unentschieden.",
    bild: { url: IMAGES.fans, alt: "Derby Berlin Fans", credit: "Foto: Schneider" },
    datum: "2025-01-28T14:00:00Z",
    kategorie: "spielbericht",
    ligaId: "berlin-liga",
    autor: { name: "Jan Westphal" },
    lesedauer: 5,
    tags: ["Berlin-Liga", "Derby", "Berlin"],
  },
  {
    id: "29",
    titel: "Jugendarbeit trägt Früchte",
    slug: "jugendarbeit-berlin-liga",
    teaser: "Gleich drei Eigengewächse schaffen den Sprung in die erste Mannschaft.",
    bild: { url: IMAGES.ball, alt: "Fußball Nachwuchs", credit: "Foto: Krüger" },
    datum: "2025-01-27T11:00:00Z",
    kategorie: "news",
    ligaId: "berlin-liga",
    autor: { name: "Lena Hoffmann" },
    lesedauer: 3,
    tags: ["Berlin-Liga", "Nachwuchs", "Jugend"],
  },
  {
    id: "30",
    titel: "Spitzenreiter mit weißer Weste",
    slug: "spitzenreiter-berlin-liga",
    teaser: "Zehn Siege in zehn Spielen: Der Tabellenführer scheint unaufhaltsam auf dem Weg zum Titel.",
    bild: { url: IMAGES.tor, alt: "Tornetz", credit: "Foto: Hartmann" },
    datum: "2025-01-26T16:00:00Z",
    kategorie: "analyse",
    ligaId: "berlin-liga",
    autor: { name: "Sven Müller" },
    lesedauer: 4,
    tags: ["Berlin-Liga", "Tabellenführer", "Meisterschaft"],
  },
];

// Helper Funktionen
export function getArtikelByLiga(ligaId: string): Artikel[] {
  if (ligaId === "all") return artikel;
  return artikel.filter((a) => a.ligaId === ligaId);
}

export function getArtikelBySlug(slug: string): Artikel | undefined {
  return artikel.find((a) => a.slug === slug);
}

export function getFeaturedArtikel(): Artikel | undefined {
  return artikel.find((a) => a.featured);
}

export function getLatestArtikel(limit: number = 5): Artikel[] {
  return [...artikel]
    .sort((a, b) => new Date(b.datum).getTime() - new Date(a.datum).getTime())
    .slice(0, limit);
}

export function getLigaById(id: string): Liga | undefined {
  return LIGEN.find((l) => l.id === id);
}

export function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("de-DE", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
